<?php
/**
 * Processwire 'FrontendUserRegister' module
 * 
 * Frontend user register module.
 * 
 * @author pwFoo
 * @since 2015-03-10
 * 
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 */
class FrontendUserRegister extends WireData implements Module {
    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire about them
     * 
     * @return array
     */
    public static function getModuleInfo() {
        return array(
            'title' => 'FrontendUserRegister',
            'summary' => 'Frontend to register users',
            'version' => '050',
            'requires'  => 'FormHelper>=0.7.0, ProcessWire>=2.5.18, PHP>=5.4.0',
        );
    }
   
    /** @var InputfieldForm PW form object extended by FormHelper */
    protected $form;
    
    /** @var User PW user object to collect the register information */
    protected $userObj;
    
    /** @var string Previously visited page */
    protected $previousPage;

    public function init() {
        $this->buildRegisterForm();     // Build register form
        $this->loadCssJs();             // Load CSS / JS custom or default files
        $this->userObj = new User();    // Create User object

        // previous visited page
        $history = $this->session->getHistory();
        $this->previousPage = end($history)['url'];
    }
    
    public function ___register($redirect = null) {
        $redirect = ($redirect ? $redirect : $this->previousPage);
        
        if($this->form->fhProcessForm() && !empty($this->saveUser($this->userObj))) {
            $this->session->redirect($redirect, false);
        }
        return $this->form->render();
    }
        
    /**
     * Save the temp User object
     * @return User Saved User object or false
     */
    protected function ___saveUser($user) {
        if ($user->save()) {
            return $user;
        }
        return false;
    }
   
    /**
     * Build the register form with basic fields
     * @return object Processwire form object
     */
    protected function buildRegisterForm() {
        $this->form = $this->modules->get('FormHelper')->create();
        $this->form->attr('id+name', 'fuRegisterForm');
        $this->form->fhSubmitBtn->attr('value', $this->_('Register'));
        $this->form->add($this->fieldUsername());
        $this->form->add($this->fieldEmail());
        $this->form->add($this->fieldPassword());
    }
    
    /**
     * Username form field
     * @return object Username field
     */
    protected function fieldUsername() {
        $field = $this->modules->get('InputfieldText');
        $field->label = $this->_('Username');
        $field->attr('id+name', 'username');
        $field->required = 1;
        $field->fhSanitizer = 'username';
        $field->addHookAfter('processInput', function($event) {
            $field = $event->object;
            $username = $this->form->fhValue($field->name);
            
            if (empty($username))   return;
            elseif (wire('users')->count("name={$username}") == 0) {
                $this->userObj->name = $username;
            }
            else {
                $field->error(__('Username already taken!'));  
            }
        });
        return $field;
    }
    
    /**
     * Email form field
     * @return object Email field
     */
    protected function fieldEmail() {
        $field = $this->modules->get('InputfieldEmail');
        $field->label = $this->_('Email');
        $field->attr('id+name', 'email');
        $field->required = 1;
        $field->addHookAfter('processInput', function($event) {
            $field = $event->object;
            $email = $this->form->fhValue($field->name);
            
            if (empty($email))  return;
            elseif (wire('users')->count("email={$email}") == 0) {
                $this->userObj->email = $email;
            }
            else {
                $field->error(__('Email address already taken!'));
            }
        });
        return $field;
    }
    
    /**
     * Password form field
     * @return object Password field
     */
    protected function fieldPassword() {
        $field = $this->modules->get('InputfieldPassword');
        $field->label = $this->_('Password');
        $field->attr('id+name', 'password');
        $field->required = 1;
        $field->addHookAfter('processInput', function($event) {
            $field = $event->object;
            $this->userObj->pass = $field->value;
        });
        $field->addHookBefore('render', function($event) {
            $field = $event->object;
            $field->value = '';
        });
        return $field;
    }
    
    /**
     * Set / get class attributes
     */
    public function attr($key, $value = null) {
        if ($value === null) return $this->$key;
        $this->$key = $value;
    }
    
    /**
     * Load custom or default module styles / scripts
     */
    protected function loadCssJs() {
        $this->getCssJs("{$this}.css", 'styles');
        $this->getCssJs("{$this}.js", 'scripts');
    }
    
    /**
     * Load custom or default CSS / JS file
     * @param string $file Filename to load
     * @param string $type File type scripts or styles
     */
    protected function getCssJs($file, $type) {
        $custom = $this . '/' . $file;
        if (file_exists($this->config->paths->templates . $custom)) {
            $file = $this->config->urls->templates . $custom;
        }
        else {
            $file = "{$this->config->urls->FrontendUserLogin}/$file";
        }
        $this->config->$type->add($file);
    }
}