<?php
/**
 * Processwire 'FrontendUserLogin' module
 * 
 * Login and logout frontend users.
 * 
 * @author pwFoo
 * @since 2015-03-10
 * 
 * ProcessWire 2.x
 * Copyright (C) 2011 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 */
class FrontendUserLogin extends WireData implements Module {
    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire about them
     * 
     * @return array
     */
    public static function getModuleInfo() {
        return array(
            'title' => 'FrontendUserLogin',
            'summary' => 'Login and logout frontend users',
            'version' => '060',
            'requires'  => 'FormHelper>=0.7.0, ProcessWire>=2.5.18, PHP>=5.4.0',
        );
    }
    
    /** @var InputfieldForm PW form object extended by FormHelper */
    protected $form;
    
    /** @var string Login username */
    protected $user;
    
    /** @var string Login password */
    protected $pass;
    
    /** @var string Previously visited page */
    protected $previousPage;

    /**
     * module initialization, required by module interface
     */
    public function init() {
        $this->buildLoginForm();    // Build login form
        $this->loadCssJs();         // Load CSS / JS custom or default files
        //
        // previous visited page
        $history = $this->session->getHistory();
        $this->previousPage = end($history)['url'];
    }
    
    // js / css handling aus FrontendUser.class.php übernehmen !!!
    
    public function ___login($redirect = null) {
        $redirect = ($redirect ? $redirect : $this->previousPage);
        
        if($this->form->fhProcessForm()) {
            $result = $this->auth($this->user, $this->pass);
            if ($result === true) {
                $this->session->redirect($redirect, false);     // Login sucessful
            }
            else {
                $this->form->fhSubmitBtn->error($result);       // login error / login throttle       
            }
        }
        return $this->form->render();
    }

        /**
     * Handling and prepare logout process
     * @param string $redirect Destination after logout
     */
    public function logout($redirect = null) {
        $redirect = ($redirect ? $redirect : $this->previousPage);
        $this->session->logout();
        $this->session->redirect($redirect, false);
    }
    
    /**
     * Execute login with error handling
     * @return true|string True if sucessfully logged in or an error message
     */
    protected function ___auth($user, $pass) {
        try {
            $result = $this->session->login($user, $pass);
            if ($result instanceof User) {
                return true;
            }
            return $this->_('Login failed!');
        }
        catch(Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Build the login form with basic fields
     */
    protected function buildLoginForm() {
        $this->form = $this->modules->get('FormHelper')->create();
        $this->form->attr('id+name', 'fuLoginForm');
        $this->form->fhSubmitBtn->attr('value', $this->_('Login'));
        $this->form->add($this->fieldUsername());
        $this->form->add($this->fieldPassword());
    }
    
    /**
     * Username form field
     * @return object Username field
     */
    protected function fieldUsername() {
        $field = $this->modules->get('InputfieldText');
        $field->skipLabel = 4; // Inputfield::skipLabelBlank;
        $field->placeholder = $this->_('Username');
        $field->attr('id+name', 'username');
        $field->required = 1;
        $field->fhSanitizer = 'username';
        $field->addHookAfter('processInput', function($event) {
            $field = $event->object;
            $this->user = $this->form->fhValue($field->name);
        });
        return $field;
    }
    
    /**
     * Password form field
     * @return object Password field
     */
    protected function fieldPassword() {
        $field = $this->modules->get('InputfieldText');
        $field->skipLabel = 4; // Inputfield::skipLabelBlank;
        $field->placeholder = $this->_('Password');
        $field->attr('id+name', 'password');
        $field->attr('type','password');
        $field->required = 1;
        $field->addHookAfter('processInput', function($event) {
            $field = $event->object;
            $this->pass = $field->value;
        });
        $field->addHookBefore('render', function($event) {
            $field = $event->object;
            $field->value = '';
        });
        return $field;
    }
    
    /**
     * Set / get class attributes
     */
    public function attr($key, $value = null) {
        if ($value === null) return $this->$key;
        $this->$key = $value;
    }

    /**
     * Load custom or default module styles / scripts
     */
    protected function loadCssJs() {
        $this->getCssJs("{$this}.css", 'styles');
        $this->getCssJs("{$this}.js", 'scripts');
    }
    
    /**
     * Load custom or default CSS / JS file
     * @param string $file Filename to load
     * @param string $type File type scripts or styles
     */
    protected function getCssJs($file, $type) {
        $custom = $this . '/' . $file;
        if (file_exists($this->config->paths->templates . $custom)) {
            $file = $this->config->urls->templates . $custom;
        }
        else {
            $file = "{$this->config->urls->FrontendUserLogin}/$file";
        }
        $this->config->$type->add($file);
    }
}